{ +block{tofukko_filter} }


.adimg\.net[/&:?=_]

/300x250\.
/300x250_
/300x250-
_300x250\.
_300_250_
_300_250\.
/468x60_
/468x60\.
_468x60_
_468x60\.
/468_60_
/468_60\.
_468_60\.
/728x90_
/728x90-
/728x90\.
_728x90_
_728x90\.
/728_90\.
_728_90\.
/A-affiliate2/.*
/aamsz=
/acc_random=
/ad/images/.*
/ad/img/.*
/ad_plugin\.js
/ad\.cgi\?
_ad\.html$
/ad\.js\?slot
_ad\.js
/ad\.php\?
/ad1\.
/ad2\.
/ad3\.
/ad4\.
/adbutler/.*
/adframe/.*
/adframes\.
\?adid=
/adloader\.
/adparts/.*
/adplayer\.
/ads\.cgi
_ads\.js\.
/ads\?
/ads2\.
/adsense/.*
/adsense_
/adserver/.*
/adservice\.
/adshow\?
/adspace/.*
/advertise\.
/advertise/.*
/advertisement/.*
\?affid=
/assets/ads/.*
/googleads\.
/img/ad/.*
/img/ad-
/img/ad_
/img/ads/.*
/image/ad/.*
/image/affiliate/.*
/images/ad/.*
/images/ad_
/images/ads/.*
/js/ad_
/js/ad/.*
/js/ads-
/js/ads_
/js\.ng/site=
/jquery\.meerkat\.
/koukoku/.*
/prebid/.*
/popunder\.
/www/delivery/.*
	!/afr\.php\?
	!/ajs\.php\?
	!/apu\.php\?
	!\.php\?zoneid=
[/&:?=_]zoneid=
[/&:?=_]zone_id=

-auto-ads-
/amp-ad-
/amp-analytics-
-sticky-ad-









.adskeeper\.co\.uk[/&:?=_]



.ad999\.biz[/&:?=_]
.af\.fukuishimbun\.co\.jp[/&:?=_]
.assets-momentum\.akamaized\.net[/&:?=_]
.banners\.itunes\.apple\.com[/&:?=_]
.bbchat\.tv[/&:?=_].*/bannar/
.bitflyer\.jp/Images/Affiliate/
.blogroll\.livedoor\.net/blogroll/banner/
.btopc\.jp/css/ec-468x67
.coincheck\.com/images/affiliates/
.digiket\.com/xml/ad/
.dietnavi\.com/pc/banner/
.dogma-annex\.com/media/affiliate/
.e-nls\.com/pict_af/
.free-video-movie\.com[/&:?=_]
.googlesyndication\.com/pagead/
.gunosy\.com/adnet/
.hayamimi-hobby\.com/gen-rss/
.hogei\.info[/&:?=_]
.idea-unlimited\.com/adsimg/
.imagefreak.*\.com[/&:?=_]
.mgstage\.com/afscript/
.mgstage\.com/js/mgs_Widget
.mkd777\.net/pd/
.pagead2\.googlesyndication\.com[/&:?=_]
.partner.*\.become\.co\.jp[/&:?=_]
.pikkur\.com/bn/
.pos\.baidu\.com[/&:?=_]
.queen-casino\.info/affi/
.realsrv\.com[/&:?=_]
.runative-syndicate\.com[/&:?=_]
.theta360\.com/intl/common/inc/ad_banner\.html\?

.2ch\.vet/img/ani_
.3751chat\.com/ad/
.4chan-ads\.org[/&:?=_]
.angel-bbs\.com/ssi/koukoku_
.anyporn\.com/aa/
.appget\.com/c/wp-content/themes/twentyten/js/agad2\.js\?
.arban-mag\.com/wp-content/themes/arban_v2\.5/common/js/ad\.js
.artstation\.com/p/c_assets/
.asageifuzoku\.com/img.*/top_
.asg\.to/ad/
.atwiki\.jp/common/dist/js/atwiki_autoads\.js\?
.atwiki\.jp/common/dist/js/moveads\.js\?
.bengo4\.com/module/topicsSideBanner/
.blog\.with2\.net/ad_frame\.php\?
.blogos\.com/pc/js/kotzen\.ad_fixed\.js\?
.chaberi\.com/html/br/
.chixi\.jp/img\.php\?filename=b
.chosunonline\.com/common/ifr01/
.cinematoday\.jp/widgets/
.clipstudio\.net[/&:?=_].*/banner_
.cookpad\.com/iframe/
.cosp\.jp/images/spacer\.gif
.cosp\.jp/inc/ad\.js
.cyclingtime\.com/adimg/
.daily\.jp/Koukoku/
.diced\.jp/webs/
.dl8x\.com/banner/
.dl8x\.com/product\?
.dlsite\.com/js/blog/DLsiteBlogBanner\.js
.dlsite\.com/js/blogparts\.js
.e-typing\.ne\.jp/app/ad_
.eegg\.fun/ad_html/
.eegg\.fun/iframe/
.eegg\.fun/js/
.egone\.org/js/amazon_
.enoge\.org/js/amazon_
.estar\.jp/page/ad/
.famitsu\.com[/&:?=_].*/amazon_ranking\.js
.fod\.fujitv\.co\.jp/mz/
.gakuryou\.net/fb/
.gakuryou\.net/right-banner/
.gamegift\.jp/js/ads\.js
.gameranbu\.jp/js/scrole_ad_
.gamespark\.jp/feature/advertising/
.gamewith\..*/ad/index\.js\?
.gehasoku\.com/JS/newama\.js
.gigazine\.net/pw/p\.js
.google\.com/pagead/
.google\.com/uds/\?file=ads&
.google\.com/uds/api/ads/
.mail-ads\.google\.com[/&:?=_]
.myoji-yurai\.net/images/banner/
.news\.merumo\.ne\.jp/ad/
	!2017/10/16 不具合あるかも
.gyazo\.com/direct_ads/
.hentai-foundry\.com/themes/default/js/activebar\.js
.hinative\.com/assets/banners/trek/
.horne\.red/banner/
.i-bbs\.sijex\.net/js/jquery\.scrollfollow\.js
.jalan\.net/jalan/doc/top/js/randombanner\.js
.japan\.cnet\.com/parts/frame/
.japanese\.joins\.com/HomeAds/
.jma\.go\.jp/bosai/ad/
.joysound\.com/web/src/s/ad/
.jugem\.jp/ad/
.kabutan\.jp/js/rand_ads\.js\?
.kakaku\.com[/&:?=_].*/kakakuad/
.kakaku\.com[/&:?=_].*/RdmReviewAd\.js
.kakaku\.k-img\.com[/&:?=_].*/ad/
.kakijun\.jp/js/u_kakijun_books%
.kidslink\.jp/cgi-bin/esb/main\.cgi\?
.kidslink\.jp[/&:?=_].*/dummy\.html
.koepota\.jp/img/ad/
.koepota\.jp/js/amazon\.js
.kokuban\.in/ad/
.labaq\.com/user/json/lq_amarray\.js\?
.luvul\.net/ad/
.mapion\.co\.jp.*/adOverture/
.mapion\.co\.jp.*/js/vl1\.
.mangaz\.com/virgo/adv/
.matomedane\.jp/js/adv/
.matomedane\.jp/js/right_navi/
.mdpr\.jp/imobile_iframe\.html
.medibang\.com/viewer/fixedAds/
.mgstage\.com/js/mgs_Widget\.js\?
	!minnano-av\.com
.minnano-.*\.com/top_center_bn/
.mixi\.jp[/&:?=_].*/adnetwork/
.new-akiba\.com/images/banner/
.new-akiba\.com/images/dlsite/
.new-akiba\.com/special/
.newsweekjapan\.jp/images/bnr/newsweek_ad_
.nijie\.info/js/ad\.js\?
.nijie\.net/.*/banner/
.open2ch\.net/test/dd\.cgi/
.pawoo\.net/packs/media/pawoo/images/about/banner-
.phileweb\.com/count/
.photozou\.jp/script/ad_sticky\.js\?
.piapro\.jp/images/ads/
.savevideo\.me/ads-fallback/
.server-navi\.info/cgi/book_
.sexyvoice\.org/banner/
.share-videos\.se/js/pjs\.js
.shopping\.sponichi\.co\.jp/scripts/sannex_banner_auction\.js
.tatituteto\.net/images/banner/
.tenhou\.net/ad1\.js
.tenhou\.net/ad2\.js
.tgiw\.info/amazon
.tinami\.com/ad/
.tsumanne\.net/maniax\.js
.tsumanne\.net/sa/src/sa\.js
.tv-tokyo\.co\.jp/tbcms/javascripts/ad\.js
.twitter\.com[/&:?=_].*/videoads/
.twoucan\.com/ad\?name=
.urasma\.com/dmm_
.uta-net\.com/user/phplib/js/view_jquery\.js
.utamap\.com/banner/
.vcomi\.jp/page_ad/
.wanchan\.jp/js/text_ad\.js
.webnewtype\.com/img/pc/common/spacer1\.gif
.wiki3\.jp/assets/image/yomoyama_advertisement\.png
.woopie\.jp[/&:?=_].*/banner/
.yamap\.com/ads$
.yamareco\.com/modules/yamainfo/include/aj_get_adinfo\.php
.yomoyama-bbs\.jp/image/ad_images/
.zyuken\.net/ads/
.zyuken\.net/juku_page/ads/

	!/__tm3k\.js
	!/__utm\.
/1x1\.gif\?
/ac\.php\?
/acc\.cgi\?
/acc\.php\?
/accek\.js
/access\.aspx\?
/access\.cgi
/access\.js
/access\.php
/access_check\.cgi\?
/access\?
/access2\.cgi\?
/accesslog/.*
/accessLog\.
/acclog\.
/acctag\.js
/agcount\.cgi\?
/akam/11/.*
/an\.cgi\?
/ana\.php\?
/ana_write\.php\?
/analog/.*
/analys\.js
/analysis\.js
/analytics\.js
_analytics\.js\?
/analytics\?
/analyze\.cgi\?
/analyzer\.cgi\?
/analyzer\.js
/apricot\.php\?
/astrack\.js
/assets/analytics-
/autotrack\.js
/autotrack\.custom\.js
/bcn\.gif\?
/beacon_
/beacon\?
/cdn-cgi/bm/cv/.*
/chartbeat\.js
/clickheat\.js
/co_tag\.php\?
/coolyze\.js
/csi\?v=
/custom-analytics\.js
/dcs\.gif\?
/dcw\.cgi\?
/dsw\.cgi\?
/ga_social_tracking\.js
/gaAddons\.js
/gaAddons-
/gaaddons/.*
/gatrack\.
/getlog\.
/getlog\?
/getstats\.js
/getstats\.php
/google\.analytics\.
/google-analyticator/.*
/google_tag/.*
/googleanalytics\.
/fingerprintjs2\.
/foresee/.*
/freelog\.
/hana\.cgi\?
/hitgraph\.cgi\?
/kwrite\.cgi\?
/load_js\.php\?
/log\.cgi\?
/log/cnt\.js
/log\.gif\?
/log_note\.cgi\?
/log\.php\?
/log_view\.gif\?
/log2\.php\?
/log4\.cgi\?
/logking\.cgi\?
/logset\.cgi\?
/logwrite\.cgi\?
/lunasys/analyzer/.*
/lunalys/analyzer/.*
/macgo\.js
/mag\.js
/mrlitelogger\.
/omn-js/.*
/omniture/.*
/omniture_
/php-stats\.js\.php
/piwik\.js
/piwik\.php
/pphlogger\.
/report\.cgi\?
/sextans\.cgi\?log
/sfa\.php
/sfga\.js
/sibulla/.*\.js
/sirabemasenka\.cgi\?
/spc\.gif\?
/spc\.php\?
/stats\.php
/topref\.cgi\?
/trace\.cgi\?
/track\.js
/tracker\.js
	!getginger\.jp英文法チェック入力欄
	!https://tools\.usps\.com/go/TrackConfirmAction\?qtc_tLabels1=荷物の番号 読み込まれるファイル https://tools\.usps\.com/go/styles/tracking\.css
/tracking\..*&ref=
/treport\.cgi\?
/trlink\.cgi\?
/urchin\.js
/VisitorAPI\.js
/w_js\.php$
/writelog\.php\?
/wtid\.js
/xenoLogger\.js
/xtcore\.js
/ywa\.js



.2bee\.jp.*/count\.php
.analytics\.agoda\.com[/&:?=_]
.analyze\.unfinished\.jp[/&:?=_]
.analyzer1\.digidigi\.jp[/&:?=_]
.aol\.com/ping\?
.aqtracker\.com[/&:?=_]
.bento\.agoda\.com[/&:?=_]
.blogtool\.jp/log/a\.js
.blogtoy\.net/add_log\?
.blozoo\.info/js/inouttool/blogparts\.js
.code\.usergram\.info[/&:?=_]
.confiant-integrations\.global\.ssl\.fastly\.net[/&:?=_]
.deqwas\.net[/&:?=_]
.disqus\.com/stats\.html
.dw-eu\.com\.com[/&:?=_]
	!google
	://analytics\..*/collect
.gpr\.hu/pr\.pr\?
.itgear\.jp.*/ax\.js
.just-now\.net/a\?k=
.just-now\.net/p\?k=
.l\.sharethis\.com[/&:?=_]
.l--l\.jp/in\.cgi\?
.mc\.yandex\.ru[/&:?=_]
.metrics\.brightcove\.com[/&:?=_]
.onesignal\.com/webPushAnalytics$
.sea\.pakapeko\.com[/&:?=_]
.seg\.sharethis\.com[/&:?=_]
.suteki-tool\.com/al
.suteki-tool\.com/pr
.l\.typesquare\.com[/&:?=_]
.line-cdn\.net[/&:?=_].*/torimochi\.js
.line-scdn\.net[/&:?=_].*/torimochi\.js
.tatsumi-sys\.jp.*\.asp\?uid=
.tr\.webantenna\.info[/&:?=_]
.tracer\.jp[/&:?=_]
.veritrans\.co\.jp/bcon/


.access\.news\.mynavi\.jp[/&:?=_]
.analysis1\.sbs-blog\.com[/&:?=_]
.analytics\.cocolog-nifty\.com[/&:?=_]
.analytics\.edgekey\.net[/&:?=_]
.analyzer\.wox\.cc[/&:?=_]
.analyzer2\.curecos\.com[/&:?=_]
.bc\.nhk\.jp[/&:?=_]
.bing\.com/fd/ls/
.blogos\.com/common/js/kotzen\.analytics\.js\?
.bunshun\.jp/oo/
.c\.microsoft\.com[/&:?=_]
.cnn\.co\.jp/js/aclick\.js
.cnn\.co\.jp/js/ga_social_tracking\.js
.cnn\.co\.jp/js/sitesnapi\.js
.collector\.githubapp\.com[/&:?=_]
.comicnettai\.com/js/js-analytics\.js
.counter-hosting\..*/counter\.php\?
.diamond\.jp/oo/
.etoyota\.net/include/js/measurementBeacon\.js
.facebook\.com.*/impression\.php
.facebook\.com/xti\.php\?
.fujitv\.co\.jp[/&:?=_].*/rtx/
.github\.com/_private/browser/stats
.gnavi\.co\.jp/analysis/
.ismedia\.jp/oo/
.kadokawagakugei\.com/js/ga2\.js
.kooss\.com/cgi-usr/accl/lkz\.cgi\?
.mainichi\.jp/js/an\.js
.maps\.google\.com[/&:?=_].*/stats\.js
.milmil\.cc/sys/asiato\.cgi\?
.milmil\.cc/sys/kaiseki\.cgi\?
.moeeki\.net/cgi-bin/accessmoe/accessmoe\.cgi\?
.nifty\.com/pubc0m/js/tag/_nif_tag\.js
.rover\.ebay\.com[/&:?=_]
.shop-pro\.jp/li\.php\?
.sony\.co\.jp/ct/sc\.js
.smp\.sankei\.co\.jp[/&:?=_]
.square-enix\.com/sitestratos/ss_squareenix\.js
.toyokeizai\.net/oo/
.tv-asahi\.co\.jp/common/js/analysis.*\.js
.twitter\.com/i/jot
.twitter\.com/oct\.js
.wikimedia\.org/geoiplookup
.zokugo-dict\.com[/&:?=_].*/ac\.js


.ezoic\.net[/&:?=_]


.speee-ad\.akamaized\.net[/&:?=_]

	! http://2ch-matomenews\.com/
	! http://kankokunohannou\.org/
	! http://www\.negisoku\.com/
	! https://news\.nifty\.com/
	! 他スマホ用あり






















	!微妙系
	!mobile
	!https://hobbyjapan\.co\.jp/comic/series/

/clog_ad\.js
/track\.php\?

.i2ad\.jp[/&:?=_]
.thench\.net[/&:?=_]
.banpro\.in\.coocan\.jp[/&:?=_]
.5ch\.net/_ads/
.5ch\.net/js/ad\.js\?
.bbspink\.com/js/ad\.js\?
.bbspink\.com/css/ad\.css

.akibablog\.net/ad-
.akibablog\.net/ads-
.akibablog\.net/banner-
.blog\.livedoor\.jp/geek/ad-
.blog\.livedoor\.jp/geek/button-ab\.html


.alphapolis\.co\.jp/html/ad_

.angelfire\.com/adm/
.lycos\.com/catman/init\.js



	! https://github\.com/tofukko/filter/issues/42



.150601\.fc2rs\.com[/&:?=_]
.dmm\.co\.jp/dmmad/
.dmm\.co\.jp/images/affiliate_banner/
.dmm\.co\.jp/af/
.dmm\.com/af/
	!ブログパーツ
.dmm\.com/photo/blog-parts/.*&affiliate_id=
.dmm\.co.*/js/banner_placement\.js\?affiliate_id=
.dmm\.co.*/js/placement\.js

.dtiblog\.com/pr_ad/
.dtiblog\.com.*/blog_ppv/
.dtiblog\.com.*/kokuchi/
.analyzer.*\.dtiblog\.com[/&:?=_]
.dtiblog\.com/hist_count\.php

.ero-video\.net/advert/.*

.okbp\.xyz[/&:?=_]
.bpm\.eroterest\.net[/&:?=_]
.kok\.eroterest\.net[/&:?=_]

.excite\.co\.jp/jp/ad/
.excite\.co\.jp/jp/ox/


.exploader\.net/images/nls/

.cg-foto\.jp/share/v5/img/stock_bnr_
.food-foto\.jp/share/v5/img/stock_bnr_
.model-foto\.jp/share/v5/img/stock_bnr_

.relart\.fresheye\.com[/&:?=_]
.fresheye\.com/parts/koma/parts_ad2_i\.html
.fresheye\.com[/&:?=_].*/js/v
.fresheye\.com/s\.gif

.2chan\.net/bin/.*\.htm
.2chan\.net/bin/count\.swf
.2chan\.net/bin/uuacount\.php\?.*
.2chan\.net/bin/uucount\.php

.futabanet\.jp/oo/



.nifty\.gesoten\.com/n/banner/

.adcdn\.goo\.ne\.jp[/&:?=_]
.ams900\.goo\.ne\.jp[/&:?=_]
.log000\.goo\.ne\.jp[/&:?=_]


	!hateblo\.jp,
	!hatenablog\.com,jp,
	!hatenadiary\.com,jp,org
	!言及先エントリを開くが消える


.yamakei-online\.com/new_images/adv/banner/

.atmarkit\.co\.jp[/&:?=_].*/ad\.js\?
.ednjapan\.com[/&:?=_].*/ad\.js\?
.itmedia\.co\.jp[/&:?=_].*/ad\.js\?
.itmedia\.co\.jp[/&:?=_].*/insert_articles_ad\.js
.itmedia\.co\.jp/css/sa\.js
.itmedia\.co\.jp/js/adRequest\.js
.itmedia\.jp/adsv/



/a/pop/js/.*

.ad\.kissanime\.si[/&:?=_]
.cdn4ads\.com[/&:?=_]
.d3g5ovfngjw9bw\.cloudfront\.net[/&:?=_]

.ad\.kisstvshow\.ru[/&:?=_]


.disqus\.com/ads-iframe/
.cpmstar\.com[/&:?=_]
.denetsuk\.com[/&:?=_]
.foowafoa\.com[/&:?=_]
.graizoah\.com[/&:?=_]
.roujaufu\.net[/&:?=_]
.viatepigan\.com[/&:?=_]

/settings/ad\.js
.gsspcln\.jp[/&:?=_]
.coppedex\.com[/&:?=_]
.counter2\.blog\.livedoor\.com/c\?ro=1&act=rss
.livedoor\.jp/js/c2\.js
.news\.livedoor\.com/js/ads\.
.t\.blog\.livedoor\.jp[/&:?=_]
	!blog cookie承認バナー
	! https://help\.blogpark\.jp/archives/52500714\.html

/lovehug\.js
.a\.vdo\.ai[/&:?=_]
.cogleapad\.com[/&:?=_]
.dyecowwhy\.com[/&:?=_]
.exdynsrv\.com[/&:?=_]
.eyefuneve\.com[/&:?=_]
.jiltlargosirk\.com[/&:?=_]
.lzrikate\.com[/&:?=_]
.mehebborc\.com[/&:?=_]
.netcatx\.com[/&:?=_]
.prosumsit\.com[/&:?=_]


://c\..*/c\.gif\?
.srtb\.msn\.com[/&:?=_]

.mbadw\.nan\.co\.jp[/&:?=_]
.mbadv\.nan\.co\.jp[/&:?=_]
.tool2\.nan-net\.com/exposure\.jpg



.nicosub\.net/api/dlsite/

.nimg\.jp/web/scripts/common/tracking/google_analytics\.js\?
.nimg\.jp/relive/playerbanner/
.nicovideo\.jp/api/v1/watch/.*/playerbanner$
.game\.nicovideo\.jp/atsumaru/ads/

.nikkei\.com/\.resources/k-components/rtoaster/
.nikkei\.com/api/mainos/v4/trendwatch
.nikkei\.com/fh/showad_
.nkis\.nikkei\.com[/&:?=_]
.astat\.nikkei\.com[/&:?=_]
.nikkei\..*[/&:?=_].*/SC/
.nikkei\..*[/&:?=_].*/SC2/
.nikkei\.com/\.resources/tracking/
.nikkei\.jp[/&:?=_].*/f1h_text1\.js



.pximg\.net/source/dic/javascript/side_ads\.js\?

.dynamic\.rakuten\.co\.jp[/&:?=_]
.books\.rakuten\.co\.jp/pzd_contents/js/ranking-ad/.*
.rakuten-static\.com/1/grp/banner/js/create\.js
.pzd\.rakuten\.co\.jp[/&:?=_]
.rat\.rakuten\.co\.jp[/&:?=_]
.rt\.rakuten\.co\.jp[/&:?=_]
.rakuten\.co\.jp/common00/omuniture/
.websearch\.rakuten\.co\.jp/elog\?

	!楽天銀行トップ、「お問い合わせ」の中身が表示されない
	! https://github\.com/AdguardTeam/AdguardFilters/issues/78861

.r10s\.jp/com/js/d/ad_liquid_table/
.rakuten-static\.com/1/grp/banner/js/create\.js


.ribbon\.to/alpc\.js
.ribbon\.to/rw\.php


.msgose\.com[/&:?=_]

/ad_plugin\.js
.bblog\.sso\.biglobe\.ne\.jp/js/insert-ad\.js
.blog\.seesaa\.jp/js/insert-ad\.min\.js
.blog\.seesaa\.jp/js/insert-ad-legacy\.min\.js
.t\.seesaa\.net[/&:?=_]



/ad\.min\.js
.tok2\.com/app/ad/

.cstwpush\.com[/&:?=_]
.d2swpuhpwp3khd\.cloudfront\.net[/&:?=_]
.tokyo-motion\.net/bnr/


.pokoran\.com[/&:?=_]
.wav\.tv/support/adFrame\?


/ad-inserter-
/ad-inserter/.*
/ad-invalid-
\.adrotate\.
/adrotate-
/adrotate/.*
/adtools\.js
/plugins/thirstyaffiliates/.*


/aurora-heatmap/
/aurora-heatmap-
/event-tracking\.js\?

.pixel\.wp\.com[/&:?=_]
.stats\.wp\.com[/&:?=_]
.stats\.wordpress\.com[/&:?=_]

.imgj\.xrea\.com[/&:?=_]
.value-domain\.com/xrea_header\.js
.ax\.xrea\.com[/&:?=_]

/yads\.
.ov\.yahoo\.co\.jp[/&:?=_]
.yads\.yahoo\.co\.jp[/&:?=_]
.yeas\.yahoo\.co\.jp[/&:?=_]
.shopping\.yahooapis\.jp/ShoppingWebService/
.yimg\.jp/bdv/
.yimg\.jp/images/advertising/
.yimg\.jp/images/listing/tool/yads/

.yahoo-mbga\.jp/ad/
.adserver-apne\.tidaltv\.com


.analytics\.yahoo\.co
.b0\.yahoo\.co\.jp[/&:?=_]
.b90\.yahoo\.co\.jp[/&:?=_]
.b91\.yahoo\.co\.jp[/&:?=_]
.b92\.yahoo\.co\.jp[/&:?=_]
.b97\.yahoo\.co\.jp
.dcs\.yahoo\.co\.jp[/&:?=_]
	! 視聴履歴が残らないかも
.geo\.yahoo\.com[/&:?=_]
.logql\.yahoo\.co\.jp[/&:?=_]
.rd\.yahoo\.co\.jp[/&:?=_]
.visit\.geocities\.jp[/&:?=_]
.ybx\.yahoo\.co\.jp[/&:?=_]
.yahoo\.co\.jp/b\?P=
.yjtag\.jp[/&:?=_]

.s\.yimg\.jp/images/listing/tool/cv/conversion\.js
.s\.yimg\.jp/images/listing/tool/cv/ytag\.js

	! https://github\.com/tofukko/filter/issues/22
	! https://github\.com/tofukko/filter/issues/23
	! https://github\.com/AdguardTeam/AdguardFilters/issues/84106
	! https://github\.com/AdguardTeam/AdguardFilters/issues/55823

.games\.wkb\.jp/html5games/play/jewelexplode/ads-




.play\.gamepix\.com/player/ads/2\.0\.0/smart-ads\.min\.js\?






.amazon\.co\.jp/aan/
.images-amazon\.com/images/.*/browser-scripts/DA-


/amazonjs/.*
/amazonjs\.

/amazon\.js
/bestsellers_
/tinywidget\.min\.js

.2blo\.net/ama/widget/
.azlink\.sakuratan\.biz[/&:?=_]
.blozoo\.info/js/amatool/blogparts\.js
.goodpic\.com[/&:?=_].*\.ajaxamazon\.js
/azlink/.*






.affiliate\.fc2\.com/afftag
.affiliate\.fc2\.com/cgi-bin/banner\.cgi\?
.affiliate\.fc2\.com/php/vc_
.aimg\.fc2\.com[/&:?=_]
.assys01\.fc2\.com[/&:?=_]
.fc2\.com[/&:?=_].*/fc2cart/banner_
.fc2\.com/.*/ad_
.fc2\.com/css/blog/entry_adult\.css
.fc2\.com/exchange\.
.fc2\.com/fc2web\.html
.fc2\.com/footer/footer\.php\?
.fc2\.com/footer/footer2\.php\?
.fc2\.com/header\.php\?
.fc2\.com/i/image/janre\.js
.fc2\.com/image/banner/
.fc2\.com/js/blog/headbar_ad_load\.js\?
.fc2\.com/share/image/banner_

.fc2\.com/video/img/b/
.fc2\.com/static/video/js/plr/tg/
.fc2\.com/video/.*/banner/
.video\.fc2\.com/a/pagead/
.video\.fc2\.com/pagead/

.live\.fc2\.com/friendlyAd\.php\?

.vip\.chps-api\.fc2\.com/apis/footer/




.analyzer.*\.fc2\.com/analyzercook\.js\?
.analyzer.*\.fc2\.com[/&:?=_].*/ana/
.cnt\.fc2web\.com[/&:?=_]
.fc2\.com/ana/
.media\.fc2\.com[/&:?=_]
.media5\.fc2\.com[/&:?=_]
.search\.fc2\.com/fc2se\.js


.ameba\.jp/ad/
.ameba\.jp/adwords/adwords\.js
.ameba\.jp/ameblo/pc/js/bigfooter-
.ameba\.jp/analytics/
.ameba\.jp/blog/xml/mk_data/official/
.amebaowndme\.com[/&:?=_].*/pureAds$
	! https://github\.com/tofukko/filter/issues/14

.ad\.abema\.io[/&:?=_]
.abema-adx\.ameba\.jp[/&:?=_]

.bizad\.nikkeibp\.co\.jp[/&:?=_]
.trendy\.nikkeibp\.co\.jp/dag/iframead/
.nikkeibp\.co\.jp[/&:?=_].*/s_code


.google\.co\.jp/pagead/
.youtube\.com[/&:?=_].*=adunit&
.youtube\.com/get_midroll_

/log_event\?
.youtube\.com/api/stats/atr
.youtube\.com/api/stats/delayplay\?
.youtube\.com/api/stats/qoe\?
.youtube\.com/ptracking\?


.tpc\.googlesyndication\.com[/&:?=_]
.youtube\.com/pagead/


/__sys__inactive_message\.js
.adc\.shinobi\.jp[/&:?=_]
.adm\.shinobi\.jp[/&:?=_]
.asumi\.shinobi\.jp[/&:?=_]
/bin/ll\?
^http://ct1\..*\.jp/sc/
^http://ct2\..*\.jp/sc/
^http://ct1\..*\.com/sc/
^http://ct2\..*\.com/sc/
.bar1\.shinobi\.jp[/&:?=_]
.omt\.shinobi\.jp[/&:?=_]
.rcm\.shinobi\.jp[/&:?=_]
.analysis\.shinobi\.jp/ninja_ar/
.ba1\.shinobi\.jp[/&:?=_]
.v2st\.shinobi\.jp[/&:?=_]
.vis1\.shinobi\.jp[/&:?=_]
.vis1\.shinobi\.jp/js/
.vis1\.shinobi\.jp/jsr/






.bipblog\.com/js/amatop\.js
.bipblog\.com/aa/ABtest/

.figsoku\.net/rank/load\.php\?


.vipsister23\.com/randamad

.jin115\.com/js/amazon_



.blog\.livedoor\.jp/hamusoku.*/amazon

.fc2\.com/w/o/r/workingnews/meerkat_side_double_js2\.js


.majikichi\.com/js/dlsite_widget\.js
.majikichi\.com/js/rad_head_

/js/cm_anpop\.js
/js/cm_rank_widget\.js





/ht\.js\?site_
.phncdn\.com/stattracker-

.phncdn\.com/www-static/js/ph-tracking\.js\?
.phncdn\.com/www-static/js/htmlPauseRoll/






.xhamster\.com/cnt\.php\?
.xhcdn\.com/js/m\.js

.static-ec\.xhcdn\.com/id2/swf/.*
.xhcdn\.com[/&:?=_].*/ads_


.xvideos\.com/in\.php\?




.ashemaletube\.com/ast/b/









	! https://github\.com/tofukko/filter/issues/29
	!トップバナー
	!動画未練
	!記事崩れ ×ボタン
	! 全部
	! ゲーム
	! https://jbbs\.shitaraba\.net/bbs/read\.cgi/internet/25463/1598352715/120
	!http://www\.jp\.square-enix\.com/seiken2_som/news\.html
	! https://github\.com/Yuki2718/adblock/issues/17
	! https://github\.com/tofukko/filter/issues/26
	! トップバナー
	! https://github\.com/tofukko/filter/issues/35
	! 動画見れない
	! 動画見れない https://sports\.nhk\.or\.jp/olympic/
	! 前にもあったので nhk\.or\.jp 全体で許可
	! https://github\.com/Yuki2718/adblock/issues/20
	!全体的に
	!全部
	!ad
	!動画プレイヤー
	!sideランキング12345
	!できない
	!トップページ他
	! https://github\.com/tofukko/filter/issues/17 次の話へ移動できない
	!右サイド
	! https://github\.com/AdguardTeam/AdguardFilters/issues/84989
	!商品タブの切替が出来ない
	!検索結果
	!真っ白
	!
	! https://github\.com/tofukko/filter/issues/18 次の話へ移動できない
	! https://github\.com/tofukko/filter/issues/41
	! http://www\.jp\.square-enix\.com/jc3/
	! https://github\.com/uBlockOrigin/uAssets/issues/9458
	! この商品を買った人は
	! ユーザーローカルAIコメント
	! https://github\.com/tofukko/filter/issues/24 サイドバー
	! https://github\.com/easylist/easylist/pull/8193
	! カートに追加できない
	! https://github\.com/AdguardTeam/AdguardFilters/issues/78329
	! https://github\.com/AdguardTeam/AdguardFilters/issues/83956
	! TOP 株式
	! 画像
	! https://github\.com/hirorpt/filters/commit/5b41ca5e9a58de697459ef5c98132f131e887c15
	! https://github\.com/tofukko/filter/issues/40
	! https://github\.com/easylist/easylist/pull/8195
	! https://github\.com/AdguardTeam/AdguardFilters/issues/75260
        ! ユーザーローカルAIコメント
	! IID 検索バー
	! 再生が始まらない
	! https://github\.com/AdguardTeam/AdguardFilters/issues/84989
        ! https://github\.com/tofukko/filter/issues/44
	! https://github\.com/tofukko/filter/issues/39
	! https://github\.com/easylist/easylist/pull/6920
	!
	! https://github\.com/easylist/easylist/pull/7907
	! https://github\.com/tofukko/filter/issues/38
	!ランキングは消さないでおこう
	! https://github\.com/tofukko/filter/issues/13 ページ移動しない
	! https://github\.com/easylist/easylist/pull/8202
	! 右側の勝率などの欄が非表示
	! 全部
	!ポイント貯めるサイト
	! https://github\.com/tofukko/filter/issues/15 あなたにおすすめ
	! 予約するポップアップ
	!申し込みランキング
	!注目アバター
	!TOP 総合ランキング
	!サムネイルが表示されない
	! 地図が無反応 
	! https://github\.com/tofukko/filter/issues/37
	!https://tabelog\.com/tokyo/map/ お店のリストと地図が出ない
	!ロックされたときとか
	!動画見れない
	! https://github\.com/tofukko/filter/issues/25
	! キャンペーンバナー
	! https://github\.com/hirorpt/filters/commit/5382bdeaf36476e17f5d8ab8f101c8ba26a3a7c9
	! https://www\.epson\.jp/products/dreamio/ehtw8400/ 製品画像

	!Minecraft ビーコン画像

	! ヤフオクへのリンク
	!header
	!Amazon誘導ページ 紙で読む
	! https://github\.com/tofukko/filter/issues/28 サイドバー
	!https://www\.kadokawa\.co\.jp/product/322003000737/
	! サイドバー
        ! https://github\.com/tofukko/filter/issues/11
	!画像リスト最大化 ついでに、編集部が選ぶ関連記事も横幅いっぱいに広げる
	! https://github\.com/tofukko/filter/issues/11 サイドバー
	!header辺り
	!記事
	!記事
	!本文
	! https://github\.com/tofukko/filter/issues/12 float



/ad-page/dfp\.js
/modal-dist/index\.js



















{ +filter{tofukko_filter} }
*
{ -block }
.pics\.dmm\.com/af/dmmad/.*/dmm0.*\.jpg
.image\.www\.rakuten\.co\.jp/com/js/d/
.cdn\.reverso\.net/abp/v1/Static/JS/advertising\.js\?
.images-fe\.ssl-images-amazon\.com[/&:?=_].*/beacon\._TTW_\.svg
.vip\.chps-api\.fc2\.com/apis/imageViewer/access\?
.xvideos\.com/video-download/
.www\.xvideos\.com/video-get-comments/
.ad-link\.jp.*/index\.php\?
.coremetrics\.com.*/eluminate\.js
.files\.mycloud\.com/js/analytics/google_analytics\.js
.rss\.solty\.biz/
.twitter\.com/account/access\?
.tsyndicate\.com/sdk/v1/n\.js
.yimg\.jp[/&:?=_].*/lib2obf_.*\.js
.yimg\.jp/bdv/yahoo/javascript/gyao/clover\.js\?
{ -block +handle-as-image }
.webryblog\.biglobe\.ne\.jp/images/ad/
.amazon-adsystem\.com/widgets/q\?
.images-amazon\.com[/&:?=_].*/beacon/BeaconSprite-
.ssl-images-amazon\.com[/&:?=_].*/beacon/BeaconSprite-
.cm-widget\.nakanohito\.jp/img/
.47club\.jp[/&:?=_].*/images/ad/
.47club\.jp[/&:?=_].*/images/ad_
.amazonaws\.com[/&:?=_].*/images/ad/
.amazonaws\.com[/&:?=_].*/images/ad_
.accesstrade\.net/m/m_img/
.affiliate\.dmm\.com/img/ad_about_ad/
.afi-b\.com/assets/dist/img/general/top/img/ad/
.aiasahi\.jp/ads/
.asahi\.com/ad/
.asahi\.com/ads/
.asahi\.com[/&:?=_].*/img/ad/
.ascii\.jp/img/ad/
.cinema\.pia\.co\.jp/img/ad/
.rd\.yahoo\.co\.jp/jpr_sports/sumo_pickup/
.utamap\.com/banner/dvd\.jpg
.utamap\.com/banner/y_ran_
.vector\.co\.jp/img_cache/tq/p/service/special/sale/gachi/images/
.hydra-media\.cursecdn\.com/minecraft-ja\.gamepedia\.com/.*/Beacon
.atwikiimg\.com/www26\.atwiki\.jp/minecraft/.*/beacon\.png
